

import { Inter } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Biz Buddy",
  description: "Generated by the Biz Buddy Company",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
    <head>
    <title>Biz Buddy</title>
    <meta name="description" content="Create flashcard from your text"/>
    </head>
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
    </ClerkProvider>
  );
}
